-- ================================================================
-- UTEQ SMART PARKING
-- Base de datos de apoyo para la práctica React + CoreUI + Supabase
-- Datos académicos tomados del CSV proporcionado por el docente.
-- Matrículas, vehículos y registros de estacionamiento: SIMULADOS.
-- ================================================================

begin;

-- ----------------------------------------------------------------
-- 1. TABLA VEHICULOS
-- Una sola tabla reúne el vehículo y los datos de su propietario.
-- ----------------------------------------------------------------
create table if not exists public.vehiculos (
  id bigint generated by default as identity primary key,
  placa varchar(8) not null unique,
  marca text not null,
  modelo text not null,
  anio smallint not null check (anio between 1990 and 2035),
  color text not null,
  tipo text not null default 'AUTOMOVIL'
    check (tipo in ('AUTOMOVIL', 'CAMIONETA', 'SUV', 'MOTOCICLETA')),
  foto_url text not null,
  foto_fuente_url text not null,
  foto_propietario_url text not null,
  cedula_propietario varchar(10) not null unique,
  cedula_enmascarada text generated always as
    ('******' || right(cedula_propietario, 4)) stored,
  propietario_nombre text not null,
  correo_institucional text not null,
  correo_microsoft text,
  autorizado boolean not null default true,
  created_at timestamptz not null default now(),
  constraint vehiculos_placa_ecuador_chk
    check (placa ~ '^[A-Z]{3}-[0-9]{4}$'),
  constraint vehiculos_cedula_chk
    check (cedula_propietario ~ '^[0-9]{10}$')
);

-- Permite volver a ejecutar esta versión sobre una tabla creada con una
-- versión anterior del script que todavía no tenía la foto del propietario.
alter table public.vehiculos
  add column if not exists foto_propietario_url text;

create index if not exists idx_vehiculos_propietario
  on public.vehiculos (propietario_nombre);

create index if not exists idx_vehiculos_marca_modelo
  on public.vehiculos (marca, modelo);

-- ----------------------------------------------------------------
-- 2. TABLA PUESTOS
-- Distribución visual: cuatro columnas (A, B, C y D), 20 puestos
-- por columna. sensor_id_rtdb coincide con el nodo usado en Firebase.
-- ----------------------------------------------------------------
create table if not exists public.puestos (
  id smallint generated by default as identity primary key,
  codigo varchar(3) not null unique,
  columna char(1) not null check (columna in ('A', 'B', 'C', 'D')),
  numero smallint not null check (numero between 1 and 20),
  sensor_id_rtdb text not null unique,
  ruta_firebase text not null unique,
  estado text not null default 'DISPONIBLE'
    check (estado in ('DISPONIBLE', 'OCUPADO', 'RESERVADO', 'FUERA_SERVICIO')),
  distancia_cm numeric(6,2),
  ultima_actualizacion timestamptz,
  created_at timestamptz not null default now(),
  unique (columna, numero)
);

create index if not exists idx_puestos_estado
  on public.puestos (estado);

-- ----------------------------------------------------------------
-- 3. TABLA REGISTROS_ESTACIONAMIENTO
-- Preparada para recibir en el futuro eventos del detector de placas
-- y de los sensores. En esta práctica no se visualiza esta tabla.
-- ----------------------------------------------------------------
create table if not exists public.registros_estacionamiento (
  id bigint generated by default as identity primary key,
  codigo_registro varchar(12) not null unique,
  vehiculo_id bigint not null
    references public.vehiculos(id) on update cascade on delete restrict,
  puesto_id smallint not null
    references public.puestos(id) on update cascade on delete restrict,
  placa_detectada varchar(8) not null,
  sensor_id_rtdb text not null,
  fecha_entrada timestamptz not null,
  fecha_salida timestamptz,
  duracion_minutos integer check (duracion_minutos is null or duracion_minutos >= 0),
  distancia_cm_entrada numeric(6,2),
  estado text not null default 'ACTIVO'
    check (estado in ('ACTIVO', 'FINALIZADO', 'ANULADO')),
  observacion text,
  created_at timestamptz not null default now(),
  constraint registros_fechas_chk
    check (fecha_salida is null or fecha_salida >= fecha_entrada),
  constraint registros_salida_estado_chk
    check (
      (estado = 'ACTIVO' and fecha_salida is null)
      or (estado in ('FINALIZADO', 'ANULADO') and fecha_salida is not null)
    )
);

create index if not exists idx_registros_vehiculo
  on public.registros_estacionamiento (vehiculo_id);

create index if not exists idx_registros_puesto
  on public.registros_estacionamiento (puesto_id);

create index if not exists idx_registros_fecha_entrada
  on public.registros_estacionamiento (fecha_entrada desc);

-- Solo puede existir un uso activo por vehículo y por puesto.
create unique index if not exists uq_registro_activo_vehiculo
  on public.registros_estacionamiento (vehiculo_id)
  where estado = 'ACTIVO';

create unique index if not exists uq_registro_activo_puesto
  on public.registros_estacionamiento (puesto_id)
  where estado = 'ACTIVO';

-- ----------------------------------------------------------------
-- 4. CARGA DE LOS 38 VEHICULOS Y PROPIETARIOS
-- Las imágenes provienen de archivos de Wikimedia Commons y corresponden
-- a la marca y modelo indicados. Las placas son ficticias con formato EC.
-- ----------------------------------------------------------------
insert into public.vehiculos (
  cedula_propietario,
  propietario_nombre,
  correo_institucional,
  correo_microsoft,
  placa,
  marca,
  modelo,
  anio,
  color,
  tipo,
  foto_url,
  foto_fuente_url,
  foto_propietario_url
)
values
  ('1208595122', 'AGURTO MACIAS RONALD STEVEN', 'ragurtom@uteq.edu.ec', 'ragurtom@msuteq.edu.ec', 'RAA-1001', 'Toyota', 'Corolla LE', 2020, 'Blanco', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020%20Toyota%20Corolla%20LE%20standard%20front%2C%205.25.19.jpg', 'https://commons.wikimedia.org/wiki/File:2020_Toyota_Corolla_LE_standard_front,_5.25.19.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/08/30/foto_2024830153816.jpg'),
  ('1207987460', 'BALDEON CEREZO LEONARDO ALEXIS', 'lbaldeonc@uteq.edu.ec', 'lbaldeonc@msuteq.edu.ec', 'RAB-1002', 'Chevrolet', 'Sail LT', 2016, 'Plata', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chevrolet%20Sail%201.5%20LT%202016.jpg', 'https://commons.wikimedia.org/wiki/File:Chevrolet_Sail_1.5_LT_2016.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/01/13/foto_202411317434.jpg'),
  ('1207440361', 'CEDEÑO FERNANDEZ MELANY ODALYS', 'mcedenof3@uteq.edu.ec', 'mcedenof3@msuteq.edu.ec', 'RAC-1003', 'Kia', 'Rio', 2020, 'Rojo', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kia%20Rio%20%28YB%2CSC%3B%202020%29%2001.jpg', 'https://commons.wikimedia.org/wiki/File:Kia_Rio_(YB,SC;_2020)_01.jpg', 'https://sga.uteq.edu.ec/media/fotos/2026/08/15/foto_202681510190.jpg'),
  ('1250170212', 'CEREZO VALENCIA KERVIN LENIN', 'kcerezov@uteq.edu.ec', 'kcerezov@msuteq.edu.ec', 'RAD-1004', 'Hyundai', 'Accent', 2014, 'Azul', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hyundai%20Accent%20P4250861.jpg', 'https://commons.wikimedia.org/wiki/File:Hyundai_Accent_P4250861.jpg', 'https://sga.uteq.edu.ec/media/fotos/2022/05/27/foto_2022527203134.jpg'),
  ('1207856160', 'CHAVEZ ANCHUNDIA YANDRI ALEXIS', 'yandri.chavez2017@uteq.edu.ec', 'ychaveza@msuteq.edu.ec', 'RAE-1005', 'Nissan', 'Versa Advance', 2021, 'Negro', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nissan%20Versa%201.6%20Advance%202021.jpg', 'https://commons.wikimedia.org/wiki/File:Nissan_Versa_1.6_Advance_2021.jpg', 'https://sga.uteq.edu.ec/media/fotos/2022/12/07/foto_202212713953.jpg'),
  ('0959406950', 'COELLO VINCES ALEJANDRO ANTONIO', 'acoellov@uteq.edu.ec', 'acoellov@msuteq.edu.ec', 'RAF-1006', 'Mazda', 'Mazda3 Sedan', 2019, 'Gris', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2019%20Mazda%203%202.0SP%20Sedan.jpg', 'https://commons.wikimedia.org/wiki/File:2019_Mazda_3_2.0SP_Sedan.jpg', 'https://sga.uteq.edu.ec/media/fotos/2022/06/12/foto_2022612214253.jpg'),
  ('1207593383', 'FONSECA PERALTA HOWARD FERNANDO', 'hfonsecap@uteq.edu.ec', 'hfonsecap@msuteq.edu.ec', 'RAG-1007', 'Renault', 'Logan Intens', 2020, 'Beige', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020%20Renault%20Logan%20Intens%20%28Colombia%29%20side%20view.png', 'https://commons.wikimedia.org/wiki/File:2020_Renault_Logan_Intens_(Colombia)_side_view.png', 'https://sga.uteq.edu.ec/media/fotos/2024/08/12/foto_2024812203311.jpg'),
  ('1206883843', 'GUANIN MACIAS SHANDER ALEXANDER', 'sguaninm@uteq.edu.ec', 'sguaninm@msuteq.edu.ec', 'RAH-1008', 'Ford', 'Fiesta Sedan', 2016, 'Verde', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2016%20Ford%20Fiesta%20Sedan%201.4L%20front%206.15.18.jpg', 'https://commons.wikimedia.org/wiki/File:2016_Ford_Fiesta_Sedan_1.4L_front_6.15.18.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/08/02/foto_20248285440.jpg'),
  ('1250887013', 'GUARANDA SALVATIERRA WILLIAM ALBERTO', 'wguarandas@uteq.edu.ec', 'wguarandas@msuteq.edu.ec', 'RAI-1009', 'Toyota', 'Corolla LE', 2020, 'Negro', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020%20Toyota%20Corolla%20LE%20standard%20front%2C%205.25.19.jpg', 'https://commons.wikimedia.org/wiki/File:2020_Toyota_Corolla_LE_standard_front,_5.25.19.jpg', 'https://sga.uteq.edu.ec/media/fotos/2022/06/12/foto_202261214143.jpg'),
  ('1207700558', 'GUERRERO AGUAYO JOY ALEXANDER', 'jguerreroa@uteq.edu.ec', 'jguerreroa@msuteq.edu.ec', 'RAJ-1010', 'Chevrolet', 'Sail LT', 2016, 'Blanco', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chevrolet%20Sail%201.5%20LT%202016.jpg', 'https://commons.wikimedia.org/wiki/File:Chevrolet_Sail_1.5_LT_2016.jpg', 'https://sga.uteq.edu.ec/media/fotos/2023/10/26/foto_20231026121025.jpg'),
  ('1250094297', 'GUERRERO OLAYA EMERSON JAHIR', 'eguerreroo@uteq.edu.ec', 'eguerreroo@msuteq.edu.ec', 'RAK-1011', 'Kia', 'Rio', 2020, 'Gris', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kia%20Rio%20%28YB%2CSC%3B%202020%29%2001.jpg', 'https://commons.wikimedia.org/wiki/File:Kia_Rio_(YB,SC;_2020)_01.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/01/13/foto_2024113134246.jpg'),
  ('1250127568', 'GUILLEN CHEVEZ HUGO ISAAC', 'hguillenc@uteq.edu.ec', 'hguillenc@msuteq.edu.ec', 'RAL-1012', 'Hyundai', 'Accent', 2014, 'Rojo', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hyundai%20Accent%20P4250861.jpg', 'https://commons.wikimedia.org/wiki/File:Hyundai_Accent_P4250861.jpg', 'https://sga.uteq.edu.ec/media/fotos/2026/03/24/foto_202632471810.jpeg'),
  ('1207244086', 'INTRIAGO PONCE JOAN MAURICIO', 'jintriagop4@uteq.edu.ec', 'jintriagop4@msuteq.edu.ec', 'RAM-1013', 'Nissan', 'Versa Advance', 2021, 'Azul', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nissan%20Versa%201.6%20Advance%202021.jpg', 'https://commons.wikimedia.org/wiki/File:Nissan_Versa_1.6_Advance_2021.jpg', 'https://sga.uteq.edu.ec/media/fotos/2022/05/15/foto_202251514550.jpg'),
  ('1251019715', 'LEON FALCONES ALESSIO ADONIS', 'aleonf2@uteq.edu.ec', 'aleonf2@msuteq.edu.ec', 'RAN-1014', 'Mazda', 'Mazda3 Sedan', 2019, 'Plata', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2019%20Mazda%203%202.0SP%20Sedan.jpg', 'https://commons.wikimedia.org/wiki/File:2019_Mazda_3_2.0SP_Sedan.jpg', 'https://sga.uteq.edu.ec/media/fotos/2025/01/16/foto_2025116184717.jpg'),
  ('1312593120', 'LOOR DE LA CRUZ RICARDO SANTIAGO', 'rloord@uteq.edu.ec', 'rloord@msuteq.edu.ec', 'RAO-1015', 'Renault', 'Logan Intens', 2020, 'Blanco', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020%20Renault%20Logan%20Intens%20%28Colombia%29%20side%20view.png', 'https://commons.wikimedia.org/wiki/File:2020_Renault_Logan_Intens_(Colombia)_side_view.png', 'https://sga.uteq.edu.ec/media/fotos/2024/12/10/foto_20241210141358.jpg'),
  ('1251239891', 'LOPEZ REINOSO CHARLES ROY', 'clopezr2@uteq.edu.ec', 'clopezr2@msuteq.edu.ec', 'RAP-1016', 'Ford', 'Fiesta Sedan', 2016, 'Negro', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2016%20Ford%20Fiesta%20Sedan%201.4L%20front%206.15.18.jpg', 'https://commons.wikimedia.org/wiki/File:2016_Ford_Fiesta_Sedan_1.4L_front_6.15.18.jpg', 'https://sga.uteq.edu.ec/media/fotos/2023/12/03/foto_2023123155431.jpg'),
  ('1206591248', 'LUCAS ALCIVAR DIEGO ARMANDO', 'dlucasa@uteq.edu.ec', 'dlucasa@msuteq.edu.ec', 'RAQ-1017', 'Toyota', 'Corolla LE', 2020, 'Gris', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020%20Toyota%20Corolla%20LE%20standard%20front%2C%205.25.19.jpg', 'https://commons.wikimedia.org/wiki/File:2020_Toyota_Corolla_LE_standard_front,_5.25.19.jpg', 'https://sga.uteq.edu.ec/media/fotos/2022/05/14/foto_2022514185745.jpg'),
  ('1727183111', 'MAWYIN ALONZO JOHN ANTHONY', 'jmawyina2@uteq.edu.ec', 'jmawyina2@msuteq.edu.ec', 'RAR-1018', 'Chevrolet', 'Sail LT', 2016, 'Rojo', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chevrolet%20Sail%201.5%20LT%202016.jpg', 'https://commons.wikimedia.org/wiki/File:Chevrolet_Sail_1.5_LT_2016.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/01/13/foto_202411313487.jpg'),
  ('1206787630', 'MOLINA MACIAS EDUARDO IGNACIO', 'emolinam@uteq.edu.ec', 'emolinam@msuteq.edu.ec', 'RAS-1019', 'Kia', 'Rio', 2020, 'Azul', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kia%20Rio%20%28YB%2CSC%3B%202020%29%2001.jpg', 'https://commons.wikimedia.org/wiki/File:Kia_Rio_(YB,SC;_2020)_01.jpg', 'https://sga.uteq.edu.ec/media/fotos/2023/02/15/foto_202321575221.jpg'),
  ('1250566351', 'MORA GANCHOZO ANGEL JANDRY', 'amorag3@uteq.edu.ec', 'amorag3@msuteq.edu.ec', 'RAT-1020', 'Hyundai', 'Accent', 2014, 'Plata', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hyundai%20Accent%20P4250861.jpg', 'https://commons.wikimedia.org/wiki/File:Hyundai_Accent_P4250861.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/01/13/foto_2024113132838.jpg'),
  ('1207664028', 'MORA GUERRA ELKYN SAUL', 'emorag@uteq.edu.ec', 'emorag@msuteq.edu.ec', 'RAU-1021', 'Nissan', 'Versa Advance', 2021, 'Blanco', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nissan%20Versa%201.6%20Advance%202021.jpg', 'https://commons.wikimedia.org/wiki/File:Nissan_Versa_1.6_Advance_2021.jpg', 'https://sga.uteq.edu.ec/media/fotos/2025/02/04/foto_2025248246.jpg'),
  ('1207432970', 'PINCAY ORELLANA JAIR RICARDO', 'jpincayo@uteq.edu.ec', 'jpincayo@msuteq.edu.ec', 'RAV-1022', 'Mazda', 'Mazda3 Sedan', 2019, 'Negro', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2019%20Mazda%203%202.0SP%20Sedan.jpg', 'https://commons.wikimedia.org/wiki/File:2019_Mazda_3_2.0SP_Sedan.jpg', 'https://sga.uteq.edu.ec/media/fotos/2022/10/13/foto_2022101320498.jpg'),
  ('1726035064', 'PLAZA PISANAN JORGE ENRIQUE', 'jplazap@uteq.edu.ec', 'jplazap@msuteq.edu.ec', 'RAW-1023', 'Renault', 'Logan Intens', 2020, 'Gris', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020%20Renault%20Logan%20Intens%20%28Colombia%29%20side%20view.png', 'https://commons.wikimedia.org/wiki/File:2020_Renault_Logan_Intens_(Colombia)_side_view.png', 'https://sga.uteq.edu.ec/media/fotos/2026/08/22/foto_202682284726.jpeg'),
  ('1208259349', 'QUIÑONEZ MENDOZA KEVIN EFRAIN', 'kquinonezm@uteq.edu.ec', 'kquinonezm@msuteq.edu.ec', 'RAX-1024', 'Ford', 'Fiesta Sedan', 2016, 'Rojo', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2016%20Ford%20Fiesta%20Sedan%201.4L%20front%206.15.18.jpg', 'https://commons.wikimedia.org/wiki/File:2016_Ford_Fiesta_Sedan_1.4L_front_6.15.18.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/01/13/foto_202411314027.jpg'),
  ('1250108303', 'RODRIGUEZ SARMIENTO JEHIEL JEREMIAS', 'jrodriguezs7@uteq.edu.ec', 'jrodriguezs7@msuteq.edu.ec', 'RAY-1025', 'Toyota', 'Corolla LE', 2020, 'Azul', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020%20Toyota%20Corolla%20LE%20standard%20front%2C%205.25.19.jpg', 'https://commons.wikimedia.org/wiki/File:2020_Toyota_Corolla_LE_standard_front,_5.25.19.jpg', 'https://sga.uteq.edu.ec/media/fotos/2025/01/17/foto_202511715188.jpg'),
  ('1207038140', 'ROSERO TRIVIÑO RODRIGO GREGORY', 'rroserot@uteq.edu.ec', 'rroserot@msuteq.edu.ec', 'RAZ-1026', 'Chevrolet', 'Sail LT', 2016, 'Plata', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chevrolet%20Sail%201.5%20LT%202016.jpg', 'https://commons.wikimedia.org/wiki/File:Chevrolet_Sail_1.5_LT_2016.jpg', 'https://sga.uteq.edu.ec/media/fotos/2023/08/01/foto_202381234158.jpg'),
  ('1206776500', 'SANCHEZ MANOTOA HENRY ESTUARDO', 'hsanchezm@uteq.edu.ec', 'hsanchezm@msuteq.edu.ec', 'RBA-1027', 'Kia', 'Rio', 2020, 'Blanco', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kia%20Rio%20%28YB%2CSC%3B%202020%29%2001.jpg', 'https://commons.wikimedia.org/wiki/File:Kia_Rio_(YB,SC;_2020)_01.jpg', 'https://sga.uteq.edu.ec/media/fotos/2022/06/13/foto_202261373550.jpg'),
  ('0953240728', 'SEGOVIA BAZURTO DIEGO ALEJANDRO', 'dsegoviab@uteq.edu.ec', 'dsegoviab@msuteq.edu.ec', 'RBB-1028', 'Hyundai', 'Accent', 2014, 'Negro', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hyundai%20Accent%20P4250861.jpg', 'https://commons.wikimedia.org/wiki/File:Hyundai_Accent_P4250861.jpg', 'https://sga.uteq.edu.ec/media/fotos/2022/05/16/foto_20225160226.jpg'),
  ('2300015910', 'SUAREZ VERA LUIS ISRAEL', 'lsuarezv2@uteq.edu.ec', 'lsuarezv2@msuteq.edu.ec', 'RBC-1029', 'Nissan', 'Versa Advance', 2021, 'Gris', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nissan%20Versa%201.6%20Advance%202021.jpg', 'https://commons.wikimedia.org/wiki/File:Nissan_Versa_1.6_Advance_2021.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/05/15/foto_202451510435.jpg'),
  ('1205285503', 'VACA CLAS KEVIN ROLANDO', 'kevin.vaca2016@uteq.edu.ec', 'kvacac@msuteq.edu.ec', 'RBD-1030', 'Mazda', 'Mazda3 Sedan', 2019, 'Rojo', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2019%20Mazda%203%202.0SP%20Sedan.jpg', 'https://commons.wikimedia.org/wiki/File:2019_Mazda_3_2.0SP_Sedan.jpg', 'https://sga.uteq.edu.ec/media/fotos/2026/05/23/foto_202652318814.png'),
  ('0942146309', 'VELEZ CARRIEL JERSON JAVIER', 'jvelezc10@uteq.edu.ec', 'jvelezc10@msuteq.edu.ec', 'RBE-1031', 'Renault', 'Logan Intens', 2020, 'Azul', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020%20Renault%20Logan%20Intens%20%28Colombia%29%20side%20view.png', 'https://commons.wikimedia.org/wiki/File:2020_Renault_Logan_Intens_(Colombia)_side_view.png', 'https://sga.uteq.edu.ec/media/fotos/2026/08/13/foto_202681321159.png'),
  ('0940541196', 'VERGARA LOZANO MARIA FERNANDA', 'mvergaral4@uteq.edu.ec', 'mvergaral4@msuteq.edu.ec', 'RBF-1032', 'Ford', 'Fiesta Sedan', 2016, 'Plata', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2016%20Ford%20Fiesta%20Sedan%201.4L%20front%206.15.18.jpg', 'https://commons.wikimedia.org/wiki/File:2016_Ford_Fiesta_Sedan_1.4L_front_6.15.18.jpg', 'https://sga.uteq.edu.ec/media/fotos/2023/12/11/foto_202312117483.jpg'),
  ('2351049941', 'VILLAFUERTE GUEVARA GIORGE IRRAEL', 'gvillafuerteg@uteq.edu.ec', 'gvillafuerteg@msuteq.edu.ec', 'RBG-1033', 'Toyota', 'Corolla LE', 2020, 'Blanco', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2020%20Toyota%20Corolla%20LE%20standard%20front%2C%205.25.19.jpg', 'https://commons.wikimedia.org/wiki/File:2020_Toyota_Corolla_LE_standard_front,_5.25.19.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/10/29/foto_20241029214530.jpg'),
  ('1250527734', 'VILLAMAR ZAMORA FRANKLIN FERNANDO', 'fvillamarz@uteq.edu.ec', 'fvillamarz@msuteq.edu.ec', 'RBH-1034', 'Chevrolet', 'Sail LT', 2016, 'Negro', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chevrolet%20Sail%201.5%20LT%202016.jpg', 'https://commons.wikimedia.org/wiki/File:Chevrolet_Sail_1.5_LT_2016.jpg', 'https://sga.uteq.edu.ec/static/images/iconos/hombre_small.png'),
  ('2300560097', 'VILLEGA ARCE GENESIS LILIBETH', 'gvillegaa@uteq.edu.ec', 'gvillegaa@msuteq.edu.ec', 'RBI-1035', 'Kia', 'Rio', 2020, 'Gris', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kia%20Rio%20%28YB%2CSC%3B%202020%29%2001.jpg', 'https://commons.wikimedia.org/wiki/File:Kia_Rio_(YB,SC;_2020)_01.jpg', 'https://sga.uteq.edu.ec/media/fotos/2023/11/30/foto_20231130135144.jpg'),
  ('1207295682', 'YEPEZ BARRO LEYDY JOMAYRA', 'lyepezb2@uteq.edu.ec', 'lyepezb2@msuteq.edu.ec', 'RBJ-1036', 'Hyundai', 'Accent', 2014, 'Rojo', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hyundai%20Accent%20P4250861.jpg', 'https://commons.wikimedia.org/wiki/File:Hyundai_Accent_P4250861.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/12/01/foto_202412121141.jpg'),
  ('1250958533', 'ZAMBRANO ZORRILLA EMILY THAIS', 'ezambranoz9@uteq.edu.ec', 'ezambranoz9@msuteq.edu.ec', 'RBK-1037', 'Nissan', 'Versa Advance', 2021, 'Azul', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nissan%20Versa%201.6%20Advance%202021.jpg', 'https://commons.wikimedia.org/wiki/File:Nissan_Versa_1.6_Advance_2021.jpg', 'https://sga.uteq.edu.ec/media/fotos/2026/05/31/foto_202653182651.png'),
  ('1250165337', 'ZAMORA BARRIGA JORDY NAHIN', 'jzamorab6@uteq.edu.ec', 'jzamorab6@msuteq.edu.ec', 'RBL-1038', 'Mazda', 'Mazda3 Sedan', 2019, 'Plata', 'AUTOMOVIL', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2019%20Mazda%203%202.0SP%20Sedan.jpg', 'https://commons.wikimedia.org/wiki/File:2019_Mazda_3_2.0SP_Sedan.jpg', 'https://sga.uteq.edu.ec/media/fotos/2024/01/13/foto_2024113141317.jpg')
on conflict (cedula_propietario) do update set
  propietario_nombre = excluded.propietario_nombre,
  correo_institucional = excluded.correo_institucional,
  correo_microsoft = excluded.correo_microsoft,
  placa = excluded.placa,
  marca = excluded.marca,
  modelo = excluded.modelo,
  anio = excluded.anio,
  color = excluded.color,
  tipo = excluded.tipo,
  foto_url = excluded.foto_url,
  foto_fuente_url = excluded.foto_fuente_url,
  foto_propietario_url = excluded.foto_propietario_url,
  autorizado = true;

alter table public.vehiculos
  alter column foto_propietario_url set not null;

-- ----------------------------------------------------------------
-- 5. CARGA DE LOS 80 PUESTOS: A01-D20
-- Ejemplos de nodos RTDB:
--   parking_A_01 -> /parqueadero/sensores/parking_A_01
--   parking_D_20 -> /parqueadero/sensores/parking_D_20
-- Los primeros cinco puestos de cada columna quedan ocupados para
-- representar 20 vehículos actualmente dentro del estacionamiento.
-- ----------------------------------------------------------------
insert into public.puestos (
  codigo,
  columna,
  numero,
  sensor_id_rtdb,
  ruta_firebase,
  estado,
  distancia_cm,
  ultima_actualizacion
)
select
  columna || lpad(numero::text, 2, '0') as codigo,
  columna,
  numero,
  'parking_' || columna || '_' || lpad(numero::text, 2, '0') as sensor_id_rtdb,
  '/parqueadero/sensores/parking_' || columna || '_' || lpad(numero::text, 2, '0') as ruta_firebase,
  case when numero <= 5 then 'OCUPADO' else 'DISPONIBLE' end as estado,
  case
    when numero <= 5 then (25 + numero * 6 + posicion * 3)::numeric(6,2)
    else (145 + numero * 5 + posicion * 7)::numeric(6,2)
  end as distancia_cm,
  -- WITH ORDINALITY devuelve posicion como bigint; make_interval exige integer.
  now() - make_interval(mins => (numero + posicion)::integer) as ultima_actualizacion
from unnest(array['A', 'B', 'C', 'D']) with ordinality as c(columna, posicion)
cross join generate_series(1, 20) as n(numero)
on conflict (codigo) do update set
  sensor_id_rtdb = excluded.sensor_id_rtdb,
  ruta_firebase = excluded.ruta_firebase,
  estado = excluded.estado,
  distancia_cm = excluded.distancia_cm,
  ultima_actualizacion = excluded.ultima_actualizacion;

-- ----------------------------------------------------------------
-- 6. REGISTROS SIMULADOS DE USO
-- 20 activos en A01-D05 y 18 históricos finalizados en A06-B10.
-- ----------------------------------------------------------------
with vehiculos_numerados as (
  select
    id,
    placa,
    row_number() over (order by id)::integer as numero_fila
  from public.vehiculos
  where cedula_propietario in (
    '1208595122','1207987460','1207440361','1250170212','1207856160',
    '0959406950','1207593383','1206883843','1250887013','1207700558',
    '1250094297','1250127568','1207244086','1251019715','1312593120',
    '1251239891','1206591248','1727183111','1206787630','1250566351',
    '1207664028','1207432970','1726035064','1208259349','1250108303',
    '1207038140','1206776500','0953240728','2300015910','1205285503',
    '0942146309','0940541196','2351049941','1250527734','2300560097',
    '1207295682','1250958533','1250165337'
  )
), datos_registro as (
  select
    v.*,
    (array['A','B','C','D'])[((v.numero_fila - 1) % 4) + 1]
      || lpad((((v.numero_fila - 1) / 4) + 1)::text, 2, '0') as codigo_puesto
  from vehiculos_numerados v
)
insert into public.registros_estacionamiento (
  codigo_registro,
  vehiculo_id,
  puesto_id,
  placa_detectada,
  sensor_id_rtdb,
  fecha_entrada,
  fecha_salida,
  duracion_minutos,
  distancia_cm_entrada,
  estado,
  observacion
)
select
  'REG-' || lpad(d.numero_fila::text, 3, '0'),
  d.id,
  p.id,
  d.placa,
  p.sensor_id_rtdb,
  case
    when d.numero_fila <= 20
      then now() - make_interval(hours => 1 + (d.numero_fila % 6))
    else now() - make_interval(days => 1 + (d.numero_fila % 12), hours => 3)
  end,
  case
    when d.numero_fila <= 20 then null
    else now() - make_interval(days => 1 + (d.numero_fila % 12))
  end,
  case when d.numero_fila <= 20 then null else 180 end,
  (28 + (d.numero_fila % 9) * 5)::numeric(6,2),
  case when d.numero_fila <= 20 then 'ACTIVO' else 'FINALIZADO' end,
  case
    when d.numero_fila <= 20 then 'Ingreso simulado; vehículo actualmente estacionado.'
    else 'Registro histórico simulado para fines académicos.'
  end
from datos_registro d
join public.puestos p on p.codigo = d.codigo_puesto
on conflict (codigo_registro) do update set
  vehiculo_id = excluded.vehiculo_id,
  puesto_id = excluded.puesto_id,
  placa_detectada = excluded.placa_detectada,
  sensor_id_rtdb = excluded.sensor_id_rtdb,
  fecha_entrada = excluded.fecha_entrada,
  fecha_salida = excluded.fecha_salida,
  duracion_minutos = excluded.duracion_minutos,
  distancia_cm_entrada = excluded.distancia_cm_entrada,
  estado = excluded.estado,
  observacion = excluded.observacion;

-- ----------------------------------------------------------------
-- 7. SEGURIDAD BASE
-- puestos y registros_estacionamiento no se exponen al frontend en
-- esta práctica (permanecen bloqueados para anon/authenticated).
-- ----------------------------------------------------------------
alter table public.vehiculos enable row level security;
alter table public.puestos enable row level security;
alter table public.registros_estacionamiento enable row level security;

revoke all on table public.vehiculos from anon, authenticated;
revoke all on table public.puestos from anon, authenticated;
revoke all on table public.registros_estacionamiento from anon, authenticated;

-- ----------------------------------------------------------------
-- 8. PANEL DE ADMINISTRACIÓN (CRUD) SOBRE VEHICULOS
-- Esta práctica amplía la anterior (solo lectura) para permitir que el
-- panel administrativo liste, cree, edite y elimine vehículos/propietarios
-- directamente desde el frontend con la clave "anon" de Supabase.
--
-- ADVERTENCIA (alcance académico): al no incluir autenticación de
-- usuarios, se habilita el CRUD completo también al rol "anon" para que
-- la práctica funcione sin backend propio. En un entorno productivo real
-- estas operaciones deben quedar detrás de Supabase Auth y una policy
-- que verifique auth.role() = 'authenticated' (o un claim de admin),
-- nunca abiertas a "anon".
-- ----------------------------------------------------------------

-- 8.1 Lectura: el panel administrativo necesita ver todas las columnas
-- (incluida la cédula completa, para poder precargarla en el formulario
-- de edición), a diferencia de la vista pública de solo lectura que
-- únicamente exponía la cédula enmascarada.
grant select, insert, update, delete on table public.vehiculos to anon, authenticated;

-- El id es identity (autogenerado) y no debe ser escrito por el cliente;
-- cedula_enmascarada y created_at son generadas/con default.
revoke update (id, cedula_enmascarada, created_at) on public.vehiculos from anon, authenticated;
revoke insert (id, cedula_enmascarada, created_at) on public.vehiculos from anon, authenticated;

drop policy if exists "Lectura publica de vehiculos autorizados" on public.vehiculos;
drop policy if exists "Panel admin: lectura total de vehiculos" on public.vehiculos;
drop policy if exists "Panel admin: crear vehiculos" on public.vehiculos;
drop policy if exists "Panel admin: editar vehiculos" on public.vehiculos;
drop policy if exists "Panel admin: eliminar vehiculos" on public.vehiculos;

-- 8.2 SELECT: el panel ve el listado completo (autorizados o no), para
-- poder administrar cualquier registro.
create policy "Panel admin: lectura total de vehiculos"
on public.vehiculos
for select
to anon, authenticated
using (true);

-- 8.3 INSERT: alta de un nuevo vehículo/propietario. Los checks de la
-- tabla (placa, cédula, año) ya validan el formato a nivel de base de
-- datos; aquí solo confirmamos que la fila insertada cumpla lo mismo.
create policy "Panel admin: crear vehiculos"
on public.vehiculos
for insert
to anon, authenticated
with check (
  placa ~ '^[A-Z]{3}-[0-9]{4}$'
  and cedula_propietario ~ '^[0-9]{10}$'
  and anio between 1990 and 2035
);

-- 8.4 UPDATE: edición de un vehículo/propietario existente.
create policy "Panel admin: editar vehiculos"
on public.vehiculos
for update
to anon, authenticated
using (true)
with check (
  placa ~ '^[A-Z]{3}-[0-9]{4}$'
  and cedula_propietario ~ '^[0-9]{10}$'
  and anio between 1990 and 2035
);

-- 8.5 DELETE: baja de un vehículo/propietario (con confirmación en el
-- frontend antes de ejecutar la petición).
create policy "Panel admin: eliminar vehiculos"
on public.vehiculos
for delete
to anon, authenticated
using (true);

commit;

-- ----------------------------------------------------------------
-- 9. VERIFICACIÓN
-- Resultado esperado: 38 vehículos, 80 puestos y 38 registros.
-- ----------------------------------------------------------------
select count(*) as total_vehiculos from public.vehiculos;
select count(*) as total_puestos from public.puestos;
select count(*) as total_registros from public.registros_estacionamiento;

select columna, count(*) as total
from public.puestos
group by columna
order by columna;

select estado, count(*) as total
from public.puestos
group by estado
order by estado;

select
  id,
  placa,
  marca,
  modelo,
  anio,
  color,
  foto_url,
  foto_propietario_url,
  cedula_enmascarada,
  propietario_nombre,
  correo_institucional,
  autorizado
from public.vehiculos
order by propietario_nombre;
